In [ ]:
# Cell 0 — Setup
import numpy as np
print("✅ NumPy ready, version:", np.__version__)


✅ NumPy ready, version: 2.0.2


In [ ]:
# Cell 1 — Exercise 1: Array Creation and Manipulation
arr1 = np.arange(10)
print(arr1)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Cell 2 — Exercise 2: Type Conversion and Array Operations
lst = [3.14, 2.17, 0, 1, 2]
arr2 = np.array(lst, dtype=int)
print(arr2)


[3 2 0 1 2]


In [ ]:
# Cell 3 — Exercise 3: Working with Multi-Dimensional Arrays
arr3 = np.arange(1, 10).reshape(3, 3)
print(arr3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Cell 4 — Exercise 4: Creating Multi-Dimensional Array with Random Numbers
arr4 = np.random.rand(4, 5)  # values between 0 and 1
print(arr4)


[[0.78166727 0.74175378 0.69297211 0.15195148 0.39159698]
 [0.98522171 0.19717756 0.79763995 0.40530582 0.29066413]
 [0.44257926 0.64119421 0.56512214 0.6673889  0.5933245 ]
 [0.10673992 0.68678291 0.40527081 0.43910621 0.18928141]]


In [ ]:
# Cell 5 — Exercise 5: Indexing Arrays
arr5 = np.array([[21,22,23,22,22],
                 [20,21,22,23,24],
                 [21,22,23,22,22]])
second_row = arr5[1]   # index 1 = second row
print(second_row)


[20 21 22 23 24]


In [ ]:
# Cell 6 — Exercise 6: Reversing elements
arr6 = np.arange(10)
reversed_arr6 = arr6[::-1]
print(reversed_arr6)


[9 8 7 6 5 4 3 2 1 0]


In [ ]:
# Cell 7 — Exercise 7: Identity Matrix
arr7 = np.eye(4)
print(arr7)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Cell 8 — Exercise 8: Sum and Average
arr8 = np.arange(10)
total = arr8.sum()
average = arr8.mean()
print("Sum:", total, "Average:", average)


Sum: 45 Average: 4.5


In [ ]:
# Cell 9 — Exercise 9: Create Array and Reshape
arr9 = np.arange(1, 21).reshape(4, 5)
print(arr9)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
# Cell 10 — Exercise 10: Conditional Selection (odd numbers)
arr10 = np.arange(10)
odd_numbers = arr10[arr10 % 2 == 1]
print(odd_numbers)


[1 3 5 7 9]
