In [1]:
# Cell 0 — Setup
import numpy as np
np.set_printoptions(precision=2, suppress=True)  # nicer printing
np.random.seed(42)  # reproducibility
print("✅ NumPy ready:", np.__version__)


✅ NumPy ready: 2.0.2


In [2]:
# Cell 1 — Exercise 1: Create 5x5 random matrix and replace max with 0
A = np.random.rand(5, 5)  # values in [0,1)
print("Original 5x5 matrix:\n", A)

# Find index of the maximum value
max_idx = np.unravel_index(np.argmax(A), A.shape)

# Replace max with 0 (make a copy to keep original if needed)
A_replaced = A.copy()
A_replaced[max_idx] = 0.0

print("\nIndex of max:", max_idx, " | max value:", float(A[max_idx]))
print("\nMatrix after replacing max with 0:\n", A_replaced)


Original 5x5 matrix:
 [[0.37 0.95 0.73 0.6  0.16]
 [0.16 0.06 0.87 0.6  0.71]
 [0.02 0.97 0.83 0.21 0.18]
 [0.18 0.3  0.52 0.43 0.29]
 [0.61 0.14 0.29 0.37 0.46]]

Index of max: (np.int64(2), np.int64(1))  | max value: 0.9699098521619943

Matrix after replacing max with 0:
 [[0.37 0.95 0.73 0.6  0.16]
 [0.16 0.06 0.87 0.6  0.71]
 [0.02 0.   0.83 0.21 0.18]
 [0.18 0.3  0.52 0.43 0.29]
 [0.61 0.14 0.29 0.37 0.46]]


In [3]:
# Cell 2 — Exercise 2: Common values between two random arrays of size 5
# Using rounding to 2 decimals so intersections are more likely to appear
x = np.random.rand(5)
y = np.random.rand(5)

x_round = np.round(x, 2)
y_round = np.round(y, 2)

common = np.intersect1d(x_round, y_round)

print("x (rounded):", x_round)
print("y (rounded):", y_round)
print("Common values:", common)


x (rounded): [0.79 0.2  0.51 0.59 0.05]
y (rounded): [0.61 0.17 0.07 0.95 0.97]
Common values: []


In [4]:
# Cell 3 — Exercise 3: Sort ascending then descending
arr = np.random.rand(10)
asc = np.sort(arr)
desc = asc[::-1]

print("Original:", np.round(arr, 2))
print("Ascending:", np.round(asc, 2))
print("Descending:", np.round(desc, 2))


Original: [0.81 0.3  0.1  0.68 0.44 0.12 0.5  0.03 0.91 0.26]
Ascending: [0.03 0.1  0.12 0.26 0.3  0.44 0.5  0.68 0.81 0.91]
Descending: [0.91 0.81 0.68 0.5  0.44 0.3  0.26 0.12 0.1  0.03]


In [5]:
# Cell 4 — Exercise 4: Random 4x4 matrix rank
M = np.random.randn(4, 4)
rank = np.linalg.matrix_rank(M)

print("Matrix 4x4:\n", M)
print("\nRank:", rank)


Matrix 4x4:
 [[-1.27  1.09  2.78  1.19]
 [ 0.22  0.88 -1.01 -1.58]
 [ 0.77 -0.54 -1.35 -0.88]
 [-1.13  0.13  0.58  0.89]]

Rank: 4


In [6]:
# Cell 5 — Exercise 5: 2D array with 1s on border and 0s inside
n = 5  # size per the example
border = np.ones((n, n), dtype=int)
border[1:-1, 1:-1] = 0
print(border)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
