In [1]:
# Cell 0 — Setup
import numpy as np
np.set_printoptions(suppress=True, precision=2)  # nicer printing
np.random.seed(42)  # reproducibility
print("✅ NumPy ready:", np.__version__)


✅ NumPy ready: 2.0.2


In [2]:
# Cell 1 — Exercise 1: 5x5 random array + min/max
arr_5x5 = np.random.rand(5, 5)  # uniform in [0, 1)
print("5x5 random array:\n", arr_5x5)
print("Min:", round(arr_5x5.min(), 2), "Max:", round(arr_5x5.max(), 2))


5x5 random array:
 [[0.37 0.95 0.73 0.6  0.16]
 [0.16 0.06 0.87 0.6  0.71]
 [0.02 0.97 0.83 0.21 0.18]
 [0.18 0.3  0.52 0.43 0.29]
 [0.61 0.14 0.29 0.37 0.46]]
Min: 0.02 Max: 0.97


In [3]:
# Cell 2 — Exercise 2: Normalize a 3x3 random matrix
M = np.random.randn(3, 3)  # standard normal entries
mu = M.mean()
sigma = M.std()
M_norm = (M - mu) / sigma

print("Original 3x3 matrix:\n", M)
print("\nNormalized 3x3 matrix:\n", M_norm)

# sanity check: approx mean 0, std 1
print("\nCheck ~0 mean, ~1 std:",
      round(M_norm.mean(), 6), round(M_norm.std(), 6))


Original 3x3 matrix:
 [[-0.63  0.6   2.56]
 [ 0.39  0.12 -0.52]
 [-0.6   0.95  0.29]]

Normalized 3x3 matrix:
 [[-1.04  0.26  2.35]
 [ 0.05 -0.24 -0.92]
 [-1.01  0.63 -0.06]]

Check ~0 mean, ~1 std: -0.0 1.0


In [4]:
# Cell 3 — Exercise 3: 50 evenly spaced in [0, 10) (exclusive of 10)
arr_1d = np.linspace(0, 10, 50, endpoint=False)
print(arr_1d)

# If you ever need to include 10, use endpoint=True
# arr_1d_inclusive = np.linspace(0, 10, 50, endpoint=True)


[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [5]:
# Cell 4 — Exercise 4: (5x3) @ (3x2)
A = np.arange(1, 1 + 5*3, dtype=float).reshape(5, 3)     # 1..15 → 5x3
B = (np.arange(1, 1 + 3*2, dtype=float).reshape(3, 2) )  # 1..6  → 3x2

C = A @ B  # same as np.dot(A, B)

print("A (5x3):\n", A)
print("\nB (3x2):\n", B)
print("\nA @ B (5x2):\n", C)


A (5x3):
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]

B (3x2):
 [[1. 2.]
 [3. 4.]
 [5. 6.]]

A @ B (5x2):
 [[ 22.  28.]
 [ 49.  64.]
 [ 76. 100.]
 [103. 136.]
 [130. 172.]]


In [6]:
# Cell 5 — Exercise 5: Create two compatible matrices and multiply
# Example: (2x4) @ (4x3) -> (2x3)
A2 = np.array([[2, 0, -1, 3],
               [1, 4,  2, 0]], dtype=float)  # shape (2,4)

B2 = np.array([[ 1,  2, 0],
               [-1,  3, 1],
               [ 4, -2, 2],
               [ 0,  5, 1]], dtype=float)     # shape (4,3)

C2 = A2 @ B2

print("A2 shape:", A2.shape, "\n", A2)
print("\nB2 shape:", B2.shape, "\n", B2)
print("\nA2 @ B2 shape:", C2.shape, "\n", C2)


A2 shape: (2, 4) 
 [[ 2.  0. -1.  3.]
 [ 1.  4.  2.  0.]]

B2 shape: (4, 3) 
 [[ 1.  2.  0.]
 [-1.  3.  1.]
 [ 4. -2.  2.]
 [ 0.  5.  1.]]

A2 @ B2 shape: (2, 3) 
 [[-2. 21.  1.]
 [ 5. 10.  8.]]
